### PR TITLE
V 0.3 -- Add hostname and coalesced ID provider tests

### PR DESCRIPTION
**Pull request by cberube**
To test:
- Review code and unit test coverage

### CODE REVIEW

**Comment by nwarlen** [comment]
AwsInstance.php Line 40: Can you use the guzzle response `json` call instead of json decoding a stringified response body?

**Comment by cberube** [comment]
@nwarlen -- nope -- no `json` method in Guzzle6 due to PSR7 compliance.

**Comment by nwarlen** [comment]
:+1: :ok: :shipit:

**Comment by jinsyaoommen** [comment]
:ok:

**Comment by notxt** [comment]
:ok: :shipit:

**Pull request merged**
